import '@/lib/orpc.server' // for pre-rendering
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/providers/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AuthProvider } from "@/lib/providers/auth-provider";
import { Providers } from '@/lib/providers/tanstack-query-provider';
import { ToasterProvider } from '@/lib/providers/toaster-provider';


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html
        suppressHydrationWarning
        lang="en"
        className={`${manrope.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange>
            <TooltipProvider>
              <Providers>
                {children}
                <ToasterProvider />
              </Providers>
            </TooltipProvider>
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
